In [1]:
%%sql
select * from postgres.pml.bonds b
order by issuer

,name,currency,issuer,isin,sector,maturity,S&P Rating,coupon,Coupon frequency,YTM (Ask),...,ask,Minimum size,Country of issue,Amount issued,Increment size,subordinated,EU Tax,W/Tax,Accrued days,Accrued interest
0,EGYPT 7.625% 20.05.2034,USD,Arab Republic of Egypt,XS3305218136,Sovereign,49084,B,7.6250,Semi-Annual,7.666441,...,99.750000,200000.0,Egypt,1000000000,1000.0,No,Yes,No,19.0,0.4024
1,EGYPT 8.625% 04.02.2030,USD,Arab Republic of Egypt,XS2989586941,Sovereign,47518,B,8.6250,Semi-Annual,6.364806,...,107.250000,200000.0,Egypt,1500000000,1000.0,No,Yes,No,125.0,2.9948
2,EGYPT 7.6% 01.03.2029,USD,Arab Republic of Egypt,XS1953057061,Sovereign,47178,B,7.6003,Semi-Annual,6.229949,...,103.375000,200000.0,Egypt,2000000000,1000.0,No,Yes,No,98.0,2.0690
3,EGYPT 5.875% 16.02.2031,USD,Arab Republic of Egypt,XS2297226545,Sovereign,47895,B,5.8750,Semi-Annual,6.531513,...,97.375000,200000.0,Egypt,1500000000,1000.0,No,Yes,No,113.0,1.8441
4,EGYPT 7.053% 15.01.2032,USD,Arab Republic of Egypt,XS2079842642,Sovereign,48228,B,7.0529,Semi-Annual,6.996045,...,100.250000,200000.0,Egypt,1000000000,1000.0,No,Yes,No,144.0,2.8212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,UTD MEXICAN 8.3% 15.08.2031,USD,United Mexican States (Mexico),US91086QAG38,Sovereign,48075,BBB,8.3000,Semi-Annual,4.328877,...,118.260500,1000.0,Mexico,1053407000,1000.0,No,Yes,No,113.0,2.6053
801,UTD MEXICAN 4.875% 19.05.2033,USD,United Mexican States (Mexico),US91087BAT70,Sovereign,48718,BBB,4.8750,Semi-Annual,5.705070,...,95.290200,200000.0,Mexico,2203576000,1000.0,No,Yes,No,171.0,2.3160
802,UTD MEXICAN 6% 13.05.2030,USD,United Mexican States (Mexico),US91087BBB53,Sovereign,47616,BBB,6.0000,Semi-Annual,4.976100,...,103.390900,200000.0,Mexico,1705844000,1000.0,No,Yes,No,25.0,0.4167
803,UTD MEXICAN 1.35% 18.09.2027,EUR,United Mexican States (Mexico),XS2135361686,Sovereign,46648,BBB,1.3500,Annual,3.255854,...,97.649000,100000.0,Mexico,750000000,1000.0,No,Yes,No,264.0,0.9764
804,US AMERICA 3.875% 15.08.2033,USD,United States of America,US91282CHT18,Sovereign,48806,AAA,3.8750,Semi-Annual,4.404929,...,96.761719,100.0,USA,122099798800,100.0,No,Yes,No,87.0,0.9161

In [2]:
df_dw = df.copy()
# Drop Column: `bid`
df_dw = df_dw.drop(columns=['bid'])
df_dw

,name,currency,issuer,isin,sector,maturity,S&P Rating,coupon,Coupon frequency,YTM (Ask),ask,Minimum size,Country of issue,Amount issued,Increment size,subordinated,EU Tax,W/Tax,Accrued days,Accrued interest
0,EGYPT 7.625% 20.05.2034,USD,Arab Republic of Egypt,XS3305218136,Sovereign,49084,B,7.6250,Semi-Annual,7.666441,99.750000,200000.0,Egypt,1000000000,1000.0,No,Yes,No,19.0,0.4024
1,EGYPT 8.625% 04.02.2030,USD,Arab Republic of Egypt,XS2989586941,Sovereign,47518,B,8.6250,Semi-Annual,6.364806,107.250000,200000.0,Egypt,1500000000,1000.0,No,Yes,No,125.0,2.9948
2,EGYPT 7.6% 01.03.2029,USD,Arab Republic of Egypt,XS1953057061,Sovereign,47178,B,7.6003,Semi-Annual,6.229949,103.375000,200000.0,Egypt,2000000000,1000.0,No,Yes,No,98.0,2.0690
3,EGYPT 5.875% 16.02.2031,USD,Arab Republic of Egypt,XS2297226545,Sovereign,47895,B,5.8750,Semi-Annual,6.531513,97.375000,200000.0,Egypt,1500000000,1000.0,No,Yes,No,113.0,1.8441
4,EGYPT 7.053% 15.01.2032,USD,Arab Republic of Egypt,XS2079842642,Sovereign,48228,B,7.0529,Semi-Annual,6.996045,100.250000,200000.0,Egypt,1000000000,1000.0,No,Yes,No,144.0,2.8212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800,UTD MEXICAN 8.3% 15.08.2031,USD,United Mexican States (Mexico),US91086QAG38,Sovereign,48075,BBB,8.3000,Semi-Annual,4.328877,118.260500,1000.0,Mexico,1053407000,1000.0,No,Yes,No,113.0,2.6053
801,UTD MEXICAN 4.875% 19.05.2033,USD,United Mexican States (Mexico),US91087BAT70,Sovereign,48718,BBB,4.8750,Semi-Annual,5.705070,95.290200,200000.0,Mexico,2203576000,1000.0,No,Yes,No,171.0,2.3160
802,UTD MEXICAN 6% 13.05.2030,USD,United Mexican States (Mexico),US91087BBB53,Sovereign,47616,BBB,6.0000,Semi-Annual,4.976100,103.390900,200000.0,Mexico,1705844000,1000.0,No,Yes,No,25.0,0.4167
803,UTD MEXICAN 1.35% 18.09.2027,EUR,United Mexican States (Mexico),XS2135361686,Sovereign,46648,BBB,1.3500,Annual,3.255854,97.649000,100000.0,Mexico,750000000,1000.0,No,Yes,No,264.0,0.9764
804,US AMERICA 3.875% 15.08.2033,USD,United States of America,US91282CHT18,Sovereign,48806,AAA,3.8750,Semi-Annual,4.404929,96.761719,100.0,USA,122099798800,100.0,No,Yes,No,87.0,0.9161

In [3]:
df_dw.describe()

,maturity,coupon,YTM (Ask),ask,Minimum size,Amount issued,Increment size,Accrued days,Accrued interest
count,805.000000,805.000000,805.000000,805.000000,8.050000e+02,8.050000e+02,8.050000e+02,799.000000,804.000000
mean,47953.669565,4.207594,5.792890,98.101911,2.268624e+05,1.254369e+10,1.313419e+05,115.106383,1.182003
std,1019.814662,2.396220,21.448901,9.774238,3.522938e+06,1.165260e+11,3.525230e+06,87.413559,1.095042
min,46188.000000,0.000000,0.288900,28.000000,1.000000e-02,5.000000e+07,1.000000e-02,1.000000,0.000000
25%,47130.000000,2.550000,3.215600,96.625000,1.000000e+03,7.500000e+08,1.000000e+03,53.000000,0.335975
50%,47898.000000,4.000000,4.394410,99.436000,1.000000e+05,1.250000e+09,1.000000e+03,101.000000,0.918300
75%,48745.000000,5.750000,5.314521,101.469800,2.000000e+05,2.100000e+09,1.000000e+03,144.000000,1.687100
max,49829.000000,12.250000,551.020408,124.875000,1.000000e+08,2.025540e+12,1.000000e+08,484.000000,8.287700